In [1]:
import numpy as np

In [2]:
x = np.array([3,4,5])
y = np.array([4,9,7])

In [3]:
x + y

array([ 7, 13, 12])

In [4]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [5]:
x.ndim

2

In [6]:
x.dtype

dtype('int64')

In [7]:
np.array([[1,2],[3.0,4]]).dtype

dtype('float64')

In [9]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [10]:
np.array([[1,2],[3,4]], float).dtype

dtype('float64')

In [11]:
x.shape

(2, 2)

In [12]:
x = np.array([1,2,3,4])
x.sum()

np.int64(10)

In [13]:
np.sum(x)

np.int64(10)

In [14]:
x = np.array([1,2,3,4,5,6])
print('beginning x:\n', x)
x_reshaped = x.reshape((2,3))
print('reshaped x:\n', x_reshaped)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [15]:
x_reshaped[0,0]

np.int64(1)

In [16]:
x_reshaped[1,2]

np.int64(6)

In [17]:
x_reshaped.shape, x_reshaped.ndim, x_reshaped.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [18]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [19]:
x**2

array([ 1,  4,  9, 16, 25, 36])

In [20]:
x**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [21]:
x = np.random.normal(size=50)
x

array([ 1.56024571,  0.16461988,  0.20039607,  0.42469381,  0.38805363,
       -0.91294616,  0.34902904,  0.72967209,  0.61607782, -2.39523047,
       -0.74068267,  0.97608493,  1.81286013,  0.07440253,  1.26150306,
        0.01076023,  0.07777063,  0.14599815,  0.98589228, -1.5573254 ,
        1.48545873,  0.56339159, -0.53350912, -0.63491674, -1.62327498,
        0.40186933, -0.2688099 , -0.61541964,  0.51663952, -1.16232565,
        0.00870524, -0.5912877 , -0.03608679,  0.54714344, -0.97687452,
       -1.78757768, -0.08822069, -0.46023608,  0.51234496, -0.18340329,
       -0.94257533,  0.61348014, -1.4284863 , -1.45097854,  2.21375375,
       -0.47751188, -0.47285992,  0.74423908,  1.36156165,  0.60503379])

In [22]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [23]:
np.corrcoef(x, y)

array([[1.        , 0.71931679],
       [0.71931679, 1.        ]])

In [25]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]
