In [1]:
import numpy as np

In [2]:
x = np.array([3,4,5])
y = np.array([4,9,7])

In [3]:
x + y

array([ 7, 13, 12])

In [4]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [5]:
x.ndim

2

In [6]:
x.dtype

dtype('int64')

In [7]:
np.array([[1,2],[3.0,4]]).dtype

dtype('float64')

In [8]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [9]:
np.array([[1,2],[3,4]], float).dtype

dtype('float64')

In [10]:
x.shape

(2, 2)

In [11]:
x = np.array([1,2,3,4])
x.sum()

np.int64(10)

In [12]:
np.sum(x)

np.int64(10)

In [13]:
x = np.array([1,2,3,4,5,6])
print('beginning x:\n', x)
x_reshaped = x.reshape((2,3))
print('reshaped x:\n', x_reshaped)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [14]:
x_reshaped[0,0]

np.int64(1)

In [15]:
x_reshaped[1,2]

np.int64(6)

In [16]:
x_reshaped.shape, x_reshaped.ndim, x_reshaped.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [17]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [18]:
x**2

array([ 1,  4,  9, 16, 25, 36])

In [19]:
x**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [20]:
x = np.random.normal(size=50)
x

array([-0.25716392,  1.1960057 ,  0.91123956, -1.48319137,  0.25857972,
       -1.19116136, -1.42124881,  0.33161178, -0.10391182, -0.10666629,
       -0.25765901,  0.8831432 , -0.52653176, -0.25710579, -0.63496326,
       -0.67720903, -0.5813111 ,  0.24945436,  1.13238097,  1.29458912,
        0.62422453, -0.56636183, -1.8304072 , -1.69091777,  1.32440214,
        0.45248316,  0.06134331, -0.34471214, -0.05348973,  1.62151778,
        0.9105391 ,  0.59641133, -0.34922186,  2.16602795,  0.88136247,
        0.2770784 , -0.37691885, -0.41160868,  1.03217929, -0.26216918,
       -1.11606696, -0.68379209, -1.3277721 ,  0.04293381, -0.1375041 ,
       -0.91587196,  1.22590868, -1.15877564, -0.53154904, -0.68203305])

In [21]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [22]:
np.corrcoef(x, y)

array([[1.        , 0.63106681],
       [0.63106681, 1.        ]])

In [23]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [24]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(np.float64(-0.1126795190952861), np.float64(-0.1126795190952861))

In [26]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

(np.float64(2.7243406406465125),
 np.float64(2.7243406406465125),
 np.float64(2.7243406406465125))

In [27]:
np.var?

Signature:      
np.var(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
    mean=<no value>,
    correction=<no value>,
)
Call signature:  np.var(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function var at 0x7caf2419f880>
File:            ~/Desktop/ISL/ISL/lib/python3.12/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a
distribution.  The variance is computed for the flattened array by
default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Array containing numbers whose variance is desired.  If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the variance is computed.  The default is to
    compute the variance of the flattened array.
    If this is 

In [29]:
np.sqrt(np.var(y)), np.std(y) 

(np.float64(1.6505576756498128), np.float64(1.6505576756498128))

In [32]:
X =rng.standard_normal((10,3))
X

array([[ 0.27644576,  0.70054489, -0.44476746],
       [-1.07640584,  0.02612483, -0.05274731],
       [ 1.40559817,  0.74740799,  0.19381565],
       [ 1.11163321, -0.20552305, -0.92589957],
       [ 0.58405831,  0.58253842, -0.21482891],
       [-0.78280858,  0.22915391, -2.49389428],
       [ 0.69012477,  0.49136826, -1.63885714],
       [ 0.06135351, -0.96409966,  0.75722104],
       [-2.03416727, -0.91449454,  0.70957999],
       [ 1.15640105, -2.15800538, -0.49803984]])